### ISSUE TITLE
Andoorra FloorPlan building 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#175]
@jascensi and I will start to work on integrating some floorplan from Andorra in the current model. This issue is a test and a place holder to start the process and have a place to discuss about the requirement that are for now (and still need to be improved) here:

https://github.com/CityScope/CS_Proxymix/wiki

@jascensi welcome to the club and don't hesitate to ask question here or even edit or comment the wiki if you think it's not clear enough.

**Comment by jascensi** [comment]
We have received several floorplans from 2 different schools (one with a high rate of covid spreading and a second one with a low rate of covid spreading).
I'll check the dxf files to meet the requirements

**Comment by agrignard** [comment]
OK great

**Comment by jascensi** [comment]
@agrignard , about dxf files and layers, is the model ok with the existance of layer that are not related to the model. For instance, "Fire prevention equipment" or " Electrical Install" layers should be locked, erased o hidden to avoid problems on the model? Or it doesn't mind?

**Comment by agrignard** [comment]
Very good question. It should not have any impact as we are filtering the layer at the initialization but anyway it will be good to test it

**Comment by agrignard** [comment]
It's ok not to clean up the file even though it might be then to heavy. How difficult is it to remove the layer? One cool solution  to streetest the tool is to have both files the one cleaned and the heavy one

**Comment by jascensi** [comment]
I have two floorplans: one from a low spreading rate school (A02_ORDINO_FRENCH_PRIMARY_SCHOOL_GROUND_FLOOR_ALL_LAYERS.dxf), and the other one from a high level spreading rate school (ANDORRAN_JUNIOR_HIGH-SCHOOL_ENCAMP_P1.dxf). Let's start with that to see if the layer naming and other stuff is working fine.
Can you create a folder in _includes_ please? I'll upload the content there.

**Comment by agrignard** [comment]
Yep the folder is here
https://github.com/CityScope/CS_Proxymix/tree/master/ProxymixABM/includes

then you can create an Andorra folder and put your dxf inside

**Comment by jascensi** [comment]
I don't think I have the proper rights to create a folder nor to upload files

**Comment by agrignard** [comment]
I just updated your permission, you can now write.

So the idea is to clone the repo, make your change (adding your files) and then committing and pushing in the master branch so we can check together if it works

**Comment by jascensi** [comment]
Done! I added the folder and files. Crossing fingers to have done that correctly!

**Comment by agrignard** [comment]
@jascensi great start, I was able to integrate the building, so thre are some slight modification that will need to be done, mostly changing the Capital Case to lower case (I think this is a kinf od AutoCad issue, from my knowledge it might be the version of Autocad youa re using,) can you try to save it in 2013 format to be sure tht the name of the layer are in Lower case? 

This is the message error I have when trying to validate the dxf , so it really seems that the layer are here they just don't have the right name

<img width="520" alt="Screenshot 2020-12-14 at 13 33 05" src="https://user-images.githubusercontent.com/3928502/102120940-3802b600-3e11-11eb-9379-6f78aff19221.png">

**Comment by jascensi** [comment]
@agrignard I changed the layers' names and saved as 2013 DXF version (I found some problems to do that on my Autocad for Mac, so we changed in Windows). I committed the changes with GitHub but I don't know if I did it well. Can you check please?

**Comment by agrignard** [comment]
I don't see the commit, did you commit and push?

**Comment by jascensi** [comment]
Jeez... I'm a noob 😓

**Comment by agrignard** [comment]
@jascensi I can now see you modifictation however it is still not working for the following reasons:

The name of the layer you are using doesn't match with the required one that can be found here
https://github.com/CityScope/CS_Proxymix/wiki as mention in this page
`````
A compatible dxf should specify at least

"Walls";"Entrance";"Offices" or "Meeting rooms";
`````

So this is what the Gama validator errors shoes 
<img width="518" alt="Screenshot 2020-12-22 at 16 09 31" src="https://user-images.githubusercontent.com/3928502/102903199-fe97ff00-443d-11eb-8f64-45d3ead7d360.png">

and this is what I see in Autocad (the layer naming convention is not respecting the Proxymix format)
<img width="418" alt="Screenshot 2020-12-22 at 16 09 24" src="https://user-images.githubusercontent.com/3928502/102903226-06f03a00-443e-11eb-89e6-254aa11840b2.png">

As an example the layer name e.g **walls** won't work it needs to be **Walls** with a capital **W**. 

So I would suggest to carefully read the naming convention and be sure that all the required layer are well defined, 

How does it sounds?

**Comment by jascensi** [comment]
My apologies @agrignard, I thought that layers should be named with small caps (from one of your previous messages). I'll change that asap

**Comment by jascensi** [comment]
Done!

**Comment by agrignard** [comment]
Not sure you psh the right file, can you push the .dxf not the .dwg?

**Comment by jascensi** [comment]
I did it but I will do it again. Maybe there is something that I'm missing out at Github

**Comment by agrignard** [comment]
It's getting there however according to this commit https://github.com/CityScope/CS_Proxymix/commit/b97df918edf4142640a0f444791ee575e6babd52 

you changed some file but not the one called building.dxf. 

The one I consider as the final one as the one called builidng.dxf in High_Covid19, Low_Covid19_Escaldes and Low_Covid19_Ordino

**Comment by jascensi** [comment]
This is weird... I have the dxf files (where I did the changes in the layers and so on) that it are in my local Github repository (picture below)
<img width="1293" alt="Captura de Pantalla 2020-12-22 a les 18 32 11" src="https://user-images.githubusercontent.com/73638146/102916638-29a54180-4484-11eb-89fe-ed30b97c0e98.png">

I pushed that on GitHub but it seems that you it didn't work. I don't really know what I'm missing but if you want to talk about that live, let me know and I'll send you a Teams link to do so

**Comment by agrignard** [comment]
What I am saying is that they don't haev the right name. they should be called ```building.dxf``` instead of ```ENCAMP_ANDORRAN_JUNIOR_HIGH-SCHOOL_1ST_FL```. Even though you can keep this file if you want but the one that will be processed by GAMA is the one called ```building.dxf```

**Comment by agrignard** [comment]
If you can just point me to the file you think are right then I will take care of renaming them

**Comment by jascensi** [comment]
Just pushed the files with the right name. Crossing fingers...

**Comment by agrignard** [comment]
Ok so first good step, Gama can now "read" the building.dxf however we are not done yet ;-)

Here is what I see when I run the validateDXF.gaml model which is just here for validation prupose

<img width="668" alt="Screenshot 2020-12-22 at 19 28 38" src="https://user-images.githubusercontent.com/3928502/102921170-edf58200-4459-11eb-97b5-db94f58bbbbf.png">
<img width="953" alt="Screenshot 2020-12-22 at 19 29 42" src="https://user-images.githubusercontent.com/3928502/102921174-ef26af00-4459-11eb-8f71-a666c4f5c9cd.png">
<img width="857" alt="Screenshot 2020-12-22 at 19 30 07" src="https://user-images.githubusercontent.com/3928502/102921175-ef26af00-4459-11eb-811e-f45fb6be28fa.png">

**Comment by agrignard** [comment]
@jascensi can you have a look at this file to take example from. You should basically have the same structure.
https://github.com/CityScope/CS_Proxymix/blob/master/ProxymixABM/includes/MediaLab/building.dxf

**Comment by agrignard** [comment]
Also it would be great if you can try to follow this steps so you can run by yourself the model in GAMA. It will be much more easier and faster if you can run it by yourself.

CAn you let me know if this wiki is clear enough? If not let's udpate it
https://github.com/CityScope/CS_Proxymix/wiki

**Comment by jascensi** [comment]
Happy New Year Arnaud! I'm introducing myself into the intricacies of using and running GAMA in my own system. I'll keep you posted about updates about the DXF floorplans and their results on GAMA.

**Comment by agrignard** [comment]
Happy new year to @jascensi looking forward to seing the progress on this topic!

**Comment by agrignard** [comment]
Hi @jascensi how is everything going? I just wanted to have some update in the floor plan of the school. According to Github we stil have some trouble running the tool on it. Any chance to iterate on this?

**Comment by agrignard** [comment]
Closing this issue for now. Anyone can be free to reopen it if there is a need from Andorra on this project
